/*
  Meetup Event Radar frontend
  ---------------------------
  Static GitHub Pages app. It does not scrape Meetup from the browser.
  It reads data/events.json generated by scripts/scrape-meetup.js.
*/

const DATA_URL = "./data/events.json";

const state = {
  payload: null,
  events: [],
  filteredEvents: []
};

const els = {
  statusDot: document.querySelector("#statusDot"),
  statusText: document.querySelector("#statusText"),
  generatedMeta: document.querySelector("#generatedMeta"),
  searchBox: document.querySelector("#searchBox"),
  categoryFilter: document.querySelector("#categoryFilter"),
  groupFilter: document.querySelector("#groupFilter"),
  viewFilter: document.querySelector("#viewFilter"),
  exportButton: document.querySelector("#exportButton"),
  summaryGrid: document.querySelector("#summaryGrid"),
  groupList: document.querySelector("#groupList"),
  eventList: document.querySelector("#eventList"),
  resultMeta: document.querySelector("#resultMeta"),
  template: document.querySelector("#eventCardTemplate")
};

async function main() {
  bindEvents();
  renderLoadingState();

  try {
    const payload = await loadEvents();
    state.payload = payload;
    state.events = Array.isArray(payload.events) ? payload.events : [];

    populateFilters();
    renderGroups();
    render();
    setStatus("ok", `Loaded ${state.events.length} event(s)`);
    els.generatedMeta.textContent = formatGeneratedMeta(payload);
  } catch (error) {
    setStatus("error", "Could not load data/events.json");
    els.generatedMeta.textContent = error.message;
    renderError(error);
  }
}

function bindEvents() {
  els.searchBox.addEventListener("input", render);
  els.categoryFilter.addEventListener("change", render);
  els.groupFilter.addEventListener("change", render);
  els.viewFilter.addEventListener("change", render);
  els.exportButton.addEventListener("click", exportCsv);
}

async function loadEvents() {
  const response = await fetch(`${DATA_URL}?cacheBust=${Date.now()}`);
  if (!response.ok) {
    throw new Error(`HTTP ${response.status} while loading ${DATA_URL}`);
  }
  return response.json();
}

function populateFilters() {
  const categories = unique(state.events.map((event) => event.category).filter(Boolean)).sort();
  const groups = unique(state.events.map((event) => event.groupSlug || event.groupName).filter(Boolean)).sort();

  for (const category of categories) {
    const option = document.createElement("option");
    option.value = category;
    option.textContent = category;
    els.categoryFilter.appendChild(option);
  }

  for (const group of groups) {
    const option = document.createElement("option");
    option.value = group;
    option.textContent = titleFromSlug(group);
    els.groupFilter.appendChild(option);
  }
}

function render() {
  const events = getFilteredEvents();
  state.filteredEvents = events;
  renderSummary(events);
  renderEvents(events);
  els.exportButton.disabled = events.length === 0;
}

function getFilteredEvents() {
  const search = els.searchBox.value.trim().toLowerCase();
  const category = els.categoryFilter.value;
  const group = els.groupFilter.value;
  const view = els.viewFilter.value;
  const now = new Date();

  return state.events
    .filter((event) => {
      if (view === "upcoming" && new Date(event.startDate) < startOfToday(now)) {
        return false;
      }

      if (category !== "all" && event.category !== category) {
        return false;
      }

      if (group !== "all" && (event.groupSlug !== group && event.groupName !== group)) {
        return false;
      }

      if (search) {
        const haystack = [
          event.title,
          event.description,
          event.location,
          event.groupName,
          event.groupSlug,
          event.category,
          ...(event.matchedCategories || []).flatMap((item) => item.hits || [])
        ].join(" ").toLowerCase();

        if (!haystack.includes(search)) {
          return false;
        }
      }

      return true;
    })
    .sort((a, b) => new Date(a.startDate) - new Date(b.startDate));
}

function renderLoadingState() {
  els.summaryGrid.innerHTML = "";
  els.eventList.innerHTML = `<div class="empty-state">Loading generated event data…</div>`;
}

function renderError(error) {
  els.summaryGrid.innerHTML = "";
  els.eventList.innerHTML = `
    <div class="empty-state">
      <strong>Could not load generated data.</strong><br>
      Run <code>npm run scrape</code> locally, or let the GitHub Action create <code>data/events.json</code>.
      <br><br>${escapeHtml(error.message)}
    </div>`;
}

function renderSummary(events) {
  const categories = countBy(events, "category");
  const nextEvent = events[0];
  const onlineCount = events.filter((event) => event.isOnline).length;

  const cards = [
    { label: "Events", value: events.length, detail: `${state.payload?.daysAhead || 90}-day window` },
    { label: "Groups", value: state.payload?.groupCount || 0, detail: "Watched sources" },
    { label: "Online", value: onlineCount, detail: "Likely online events" },
    { label: "Next", value: nextEvent ? formatShortDate(nextEvent.startDate) : "—", detail: nextEvent?.title || "No upcoming event" }
  ];

  els.summaryGrid.innerHTML = cards.map((card) => `
    <article class="summary-card">
      <span>${escapeHtml(card.label)}</span>
      <strong>${escapeHtml(String(card.value))}</strong>
      <small>${escapeHtml(card.detail)}</small>
    </article>
  `).join("");

  const topCategories = Object.entries(categories)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([name, count]) => `${name}: ${count}`)
    .join(" · ");

  els.resultMeta.textContent = topCategories || "No matching events.";
}

function renderGroups() {
  const groups = state.payload?.groups || [];
  els.groupList.innerHTML = groups.map((group) => `
    <li>
      <a href="${escapeAttribute(group.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(titleFromSlug(group.slug))}</a><br>
      <small>${escapeHtml(group.slug)}</small>
    </li>
  `).join("");
}

function renderEvents(events) {
  els.eventList.innerHTML = "";

  if (events.length === 0) {
    els.eventList.innerHTML = `<div class="empty-state">No events match the current filters.</div>`;
    return;
  }

  for (const event of events) {
    const card = els.template.content.cloneNode(true);
    const title = card.querySelector(".event-title");
    title.textContent = event.title;
    title.href = event.eventUrl;

    card.querySelector(".category-pill").textContent = `${event.categoryEmoji || "📌"} ${event.category || "Other"}`;
    card.querySelector(".score-pill").textContent = `Score ${event.score ?? 0}`;
    card.querySelector(".event-description").textContent = truncate(event.description || "No description captured.", 240);
    card.querySelector(".event-date").textContent = formatLongDate(event.startDate);
    card.querySelector(".event-group").textContent = event.groupName || titleFromSlug(event.groupSlug || "Unknown group");
    card.querySelector(".event-location").textContent = event.location || "TBC";
    card.querySelector(".event-rsvps").textContent = event.rsvpCount == null ? "Unknown" : String(event.rsvpCount);

    const matchedTags = card.querySelector(".matched-tags");
    const hits = unique((event.matchedCategories || []).flatMap((item) => item.hits || [])).slice(0, 8);
    matchedTags.innerHTML = hits.map((hit) => `<span class="tag">${escapeHtml(hit)}</span>`).join("");

    els.eventList.appendChild(card);
  }
}

function exportCsv() {
  const rows = [
    ["title", "category", "score", "startDate", "group", "location", "rsvpCount", "isOnline", "eventUrl"]
  ];

  for (const event of state.filteredEvents) {
    rows.push([
      event.title,
      event.category,
      event.score,
      event.startDate,
      event.groupName || event.groupSlug,
      event.location,
      event.rsvpCount ?? "",
      event.isOnline ? "yes" : "no",
      event.eventUrl
    ]);
  }

  const csv = rows.map((row) => row.map(csvEscape).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "meetup-events.csv";
  link.click();
  URL.revokeObjectURL(url);
}

function setStatus(kind, message) {
  els.statusDot.classList.toggle("ok", kind === "ok");
  els.statusDot.classList.toggle("error", kind === "error");
  els.statusText.textContent = message;
}

function formatGeneratedMeta(payload) {
  const generated = payload.generatedAt ? formatLongDate(payload.generatedAt) : "unknown";
  const warnings = Array.isArray(payload.errors) && payload.errors.length > 0 ? ` · ${payload.errors.length} scraper warning(s)` : "";
  return `Generated ${generated}${warnings}`;
}

function formatShortDate(value) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "—";
  return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short" }).format(date);
}

function formatLongDate(value) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "Unknown";
  return new Intl.DateTimeFormat("en-GB", {
    weekday: "short",
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    timeZoneName: "short"
  }).format(date);
}

function titleFromSlug(value) {
  return String(value || "")
    .split("-")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function startOfToday(now) {
  const copy = new Date(now);
  copy.setHours(0, 0, 0, 0);
  return copy;
}

function countBy(items, key) {
  return items.reduce((acc, item) => {
    const value = item[key] || "Unknown";
    acc[value] = (acc[value] || 0) + 1;
    return acc;
  }, {});
}

function unique(items) {
  return [...new Set(items.filter(Boolean))];
}

function truncate(value, maxLength) {
  const text = String(value || "");
  return text.length <= maxLength ? text : `${text.slice(0, maxLength - 1)}…`;
}

function csvEscape(value) {
  return `"${String(value ?? "").replaceAll('"', '""')}"`;
}

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function escapeAttribute(value) {
  return escapeHtml(value).replaceAll("`", "&#096;");
}

main();
